apiVersion : apps/v1
kind : Deployment
metadata :
    name: myapi-depl
spec: 
  replicas: 2
  selector:
    matchLabels:
      app: myapi
  template:
    metadata:
      labels:
        app: myapi
    spec:
      containers:
        - name: myapi
          image: serkan1st/odev1:v3
          ports:
           - containerPort: 80