apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app-v1-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-app
      version: v1
  template:
    metadata:
      labels:
        app: web-app
        version: v1
    spec:
      containers:
       - name: web-app
         image: serkan1st/web-app:v1
         ports:
          - containerPort: 3000